/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as WithValueImport } from './routes/with-value'
import { Route as WithRefImport } from './routes/with-ref'
import { Route as SendToImport } from './routes/send-to'
import { Route as ReceptionistImport } from './routes/receptionist'
import { Route as InvokeImport } from './routes/invoke'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const WithValueRoute = WithValueImport.update({
  id: '/with-value',
  path: '/with-value',
  getParentRoute: () => rootRoute,
} as any)

const WithRefRoute = WithRefImport.update({
  id: '/with-ref',
  path: '/with-ref',
  getParentRoute: () => rootRoute,
} as any)

const SendToRoute = SendToImport.update({
  id: '/send-to',
  path: '/send-to',
  getParentRoute: () => rootRoute,
} as any)

const ReceptionistRoute = ReceptionistImport.update({
  id: '/receptionist',
  path: '/receptionist',
  getParentRoute: () => rootRoute,
} as any)

const InvokeRoute = InvokeImport.update({
  id: '/invoke',
  path: '/invoke',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/invoke': {
      id: '/invoke'
      path: '/invoke'
      fullPath: '/invoke'
      preLoaderRoute: typeof InvokeImport
      parentRoute: typeof rootRoute
    }
    '/receptionist': {
      id: '/receptionist'
      path: '/receptionist'
      fullPath: '/receptionist'
      preLoaderRoute: typeof ReceptionistImport
      parentRoute: typeof rootRoute
    }
    '/send-to': {
      id: '/send-to'
      path: '/send-to'
      fullPath: '/send-to'
      preLoaderRoute: typeof SendToImport
      parentRoute: typeof rootRoute
    }
    '/with-ref': {
      id: '/with-ref'
      path: '/with-ref'
      fullPath: '/with-ref'
      preLoaderRoute: typeof WithRefImport
      parentRoute: typeof rootRoute
    }
    '/with-value': {
      id: '/with-value'
      path: '/with-value'
      fullPath: '/with-value'
      preLoaderRoute: typeof WithValueImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/invoke': typeof InvokeRoute
  '/receptionist': typeof ReceptionistRoute
  '/send-to': typeof SendToRoute
  '/with-ref': typeof WithRefRoute
  '/with-value': typeof WithValueRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/invoke': typeof InvokeRoute
  '/receptionist': typeof ReceptionistRoute
  '/send-to': typeof SendToRoute
  '/with-ref': typeof WithRefRoute
  '/with-value': typeof WithValueRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/invoke': typeof InvokeRoute
  '/receptionist': typeof ReceptionistRoute
  '/send-to': typeof SendToRoute
  '/with-ref': typeof WithRefRoute
  '/with-value': typeof WithValueRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/invoke'
    | '/receptionist'
    | '/send-to'
    | '/with-ref'
    | '/with-value'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/invoke'
    | '/receptionist'
    | '/send-to'
    | '/with-ref'
    | '/with-value'
  id:
    | '__root__'
    | '/'
    | '/invoke'
    | '/receptionist'
    | '/send-to'
    | '/with-ref'
    | '/with-value'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InvokeRoute: typeof InvokeRoute
  ReceptionistRoute: typeof ReceptionistRoute
  SendToRoute: typeof SendToRoute
  WithRefRoute: typeof WithRefRoute
  WithValueRoute: typeof WithValueRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InvokeRoute: InvokeRoute,
  ReceptionistRoute: ReceptionistRoute,
  SendToRoute: SendToRoute,
  WithRefRoute: WithRefRoute,
  WithValueRoute: WithValueRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/invoke",
        "/receptionist",
        "/send-to",
        "/with-ref",
        "/with-value"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/invoke": {
      "filePath": "invoke.tsx"
    },
    "/receptionist": {
      "filePath": "receptionist.tsx"
    },
    "/send-to": {
      "filePath": "send-to.tsx"
    },
    "/with-ref": {
      "filePath": "with-ref.tsx"
    },
    "/with-value": {
      "filePath": "with-value.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
